---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rmyha174/public_html
    - /bin/cp /home/rmyha174/repositories/cemetery/dist/*.html $DEPLOYPATH
    - /bin/cp -R /home/rmyha174/repositories/cemetery/dist/assets $DEPLOYPATH
    - /bin/rm -R /home/rmyha174/repositories/cemetery/src $DEPLOYPATH
    - /bin/rm -R /home/rmyha174/repositories/cemetery/node_modules $DEPLOYPATH
    - /bin/rm -R /home/rmyha174/repositories/cemetery/.vscode $DEPLOYPATH
    - /bin/rm /home/rmyha174/repositories/cemetery/.gitignore $DEPLOYPATH
    - /bin/rm /home/rmyha174/repositories/cemetery/.gulpfile.js $DEPLOYPATH
    - /bin/rm /home/rmyha174/repositories/cemetery/package-lock.json $DEPLOYPATH
    - /bin/rm /home/rmyha174/repositories/cemetery/package.json $DEPLOYPATH
