---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rmyha174/public_html
    - /bin/cp /home/rmyha174/repositories/cemetery/dist/*.html $DEPLOYPATH
    - /bin/cp -R /home/rmyha174/repositories/cemetery/dist/assets $DEPLOYPATH
    - /bin/rm -R /home/rmyha174/repositories/cemetery/src
    - /bin/rm -R /home/rmyha174/repositories/cemetery/node_modules
    - /bin/rm -R /home/rmyha174/repositories/cemetery/.vscode
    - /bin/rm /home/rmyha174/repositories/cemetery/.gitignore
    - /bin/rm /home/rmyha174/repositories/cemetery/.gulpfile.js
    - /bin/rm /home/rmyha174/repositories/cemetery/package-lock.json
    - /bin/rm /home/rmyha174/repositories/cemetery/package.json
